# Generated by Django 4.2.4 on 2023-12-13 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_order_user_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
