# Generated by Django 4.2.4 on 2023-12-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
